// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/khv1one/go-url-shortener/internal/api"
	"github.com/khv1one/go-url-shortener/internal/clients"
	"github.com/khv1one/go-url-shortener/internal/handlers"
	"github.com/khv1one/go-url-shortener/internal/usecases"
)

// Injectors from wire.go:

func InitializeApp() api.Router {
	redisClient := clients.NewRedisClient()
	linkGenerator := usecases.NewLinkGenerator()
	shortenerHandler := handlers.NewShortenerHandler(redisClient, linkGenerator)
	router := api.NewRouter(shortenerHandler)
	return router
}
